### ISSUE TITLE
jquery-payment dependency not resolved

### ISSUE THREAD

**Issue by jeusdi** [cmer/parsley-payment#1]
I'm getting an issue when I'm trying to install it:

> Registry returned 404 for GET on https://registry.npmjs.org/jquery-payment
> 'jquery-payment' is not in the npm registry.

I've took a look on npmjs repository and `jquery-payment` doesn't exist. Nevertheless, `jquery.payment` does.

**Comment by jeusdi** [comment]
I've created a pull request.

**Comment by cmer** [comment]
Thanks a lot. It's been merged. Sorry for the delay, I didn't see this until today.
